version: 1.2
workflows:
   - name: bcftools_stats
     subclass: WDL
     primaryDescriptorPath: /bcftools_stats.wdl
     testParameterFiles:
         - /bcftools_stats.json
   - name: extract_vcf_ids
     subclass: WDL
     primaryDescriptorPath: /extract_vcf_ids.wdl
   - name: filter_vcf
     subclass: WDL
     primaryDescriptorPath: /filter_vcf.wdl
